version: '2'

networks:
  funhouse_funhouse:
    external: true

services:
  kowalski:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-timezone
    restart: always
    volumes:
      - /mnt/wisconsin/flexo:/data
    networks:
      - funhouse_funhouse
