version: '2'

networks:
  funhouse_funhouse:
    external: true

services:
  kowalski:
    env_file:
      - .env
    build: .
    restart: always
    volumes:
      - /mnt/wisconsin/europe:/data
    networks:
      - funhouse_funhouse
