version: "2"

services:
  kowalski:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-timezone
    command: ["npx", "nodemon", "index.js"]
    restart: on-failure
    volumes:
      - /Users/dillon/git/DATAS:/data
      - .:/code/
      - /code/node_modules/
