FROM mhart/alpine-node:10.7
RUN apk update && apk upgrade && apk add --no-cache tzdata file imagemagick
ENV TZ America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etclocaltime && echo $TZ > /etc/timezone
WORKDIR /code/
COPY package*.json ./
RUN npm i
COPY . .
CMD ["npm", "start"]
